FROM maildealer/rails:app

##################################
######## CHROME & FIREFOX ########
##################################
RUN apt-get update -qqy && apt-get -qqy install xvfb xdg-utils fonts-liberation libappindicator3-1 libasound2 libnspr4 libnss3 libxss1 unzip

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

RUN wget -O FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
RUN mkdir /opt/firefox
RUN tar xjf FirefoxSetup.tar.bz2 -C /opt/firefox/
RUN ln -s /opt/firefox/firefox/firefox /usr/local/sbin

###########################
########## EMOJI ##########
###########################
RUN apt-get install -y --no-install-recommends fonts-noto-color-emoji

#################################
######## Clean apt cache ########
#################################
RUN rm -rf /var/lib/apt/lists/*
